### STAGE-PROD
#==============
FROM cleverage/eav-manager:php7.2 AS release-prod
ENV SYMFONY_ENV prod

### He you can add specific stuff like php module missing
### RUN apk add -U php-foo@php php-bar@php
### Please to note that you can add a module without specify the php version
### you must suffix the module to install with @php

### STAGE-BUILD
#==============
FROM release-prod AS stage-build

### Be Careful : COPY use the .dockerignore file configuration
COPY --chown=docker:docker . .
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN composer install --no-scripts --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader

### STAGE-PROD
#==============
FROM release-prod
COPY --from=stage-build --chown=docker:docker . .

### AT the running of your container, the entrypoint will be executed and change the parameters.yml variable with
### the injection of environment variables
#-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
#  "database_host": "SF_DATABASE_HOST",
#  "database_port": "SF_DATABASE_PORT",
#  "database_name": "SF_DATABASE_NAME",
#  "database_user": "SF_DATABASE_USER",
#  "database_password": "SF_DATABASE_PASSWORD",
#  "mailer_transport": "SF_MAILER_TRANSPORT",
#  "mailer_host": "SF_MAILER_HOST",
#  "mailer_user": "SF_MAILER_USER",
#  "mailer_password": "SF_MAILER_PASSWORD",
#  "secret": "SF_SECRET",
#  "trusted_proxies": "SF_TRUSTED_PROXIES"
