imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        fingers_crossed:
            type: fingers_crossed
            action_level: warning
            handler: file
            channels: ['!translation', '!event']
        file:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            max_files: 10
            level: debug
            formatter: monolog.formatter.standard
        console:
            type: console
            channels: ['!event', '!doctrine', '!cache', '!translation']
