#services:
#    # Command needs to be declared explicitly
#    App\Command\:
#        resource: '../../../src/App/Command/*'
#        autowire: true
#        autoconfigure: true
#        public: false
